### ISSUE TITLE
Z

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/festacrevival#13]
Normally, the Z reverses the contrast from the other glyphs or what might be assumed, ie, the horizontal top and bottom are the heavier lines and the diagonal is the thinner line. Doing that, and potentially even adding a curve to the diagonal, could maybe make it as fun as the X (the X is my favourite glyph =D).

**Comment by bghryct** [comment]
We've tried the curve in the past and it ends up looking really strange. I think the reversal of the contrast is resolved. For now I'm going to mark this as closed, but feel free to re-open.
