### ISSUE TITLE
Curve Tilt — K, M

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/festacrevival#14]
I’m a little thrown off by glyphs where the angles of the stems/curves, and the resulting counter shape, is similar but not quite. Such as the top vs bottom half of the uppercase K, or the left and right half of the M. It feels not quite harmonious to me, and I wonder if adjusting it one way or another would help. This is such a rigorous and intentional alphabet — and so many of the other glyphs feel so calligraphic and confident, I’d love to see that resolved here.

**Comment by bghryct** [comment]
Could you say more about the discontinuity you're seeing?

**Comment by bghryct** [comment]
Closing this barring any further feedback.
