### ISSUE TITLE
e

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/festacrevival#15]
When seeing it in context, the lowercase e jumps out to me as not fully looking like an e, or being a bit too p-like. I think it's the only letter that in context I'm not reading for what it is.

**Comment by samarskaya** [comment]
If I look at the original logotype, the bottom of the e is more curved and with a narrower top bowl it takes up more of the space underneath it, making it more legible. The mid-line where the e bowl starts is higher. And the top is narrower.
![festac-77-edited](https://github.com/Afrotype/festacrevival/assets/8194236/f53b942c-eb56-4278-b2e2-14ba6bfa6e23)

**Comment by bghryct** [comment]
Hmm. I'm erring on the side of it being alright. I'm not seeing the 'p' in the 'e'
