### ISSUE TITLE
i j tittle 

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/festacrevival#16]
The tittle (dot) over the i and j feels a little too bland/tight/close as there’s nowhere else in the font with as tight a negative space. Raising them is the most basic suggestion. Playing around and incorporating a slanted cut somewhere is an extravagant thought.

**Comment by samarskaya** [comment]
Oooh if the top of the i and j stem was concave slightly, that'd vibe well with teh rest and create that needed space without pushing all else up. Like a little bown for the tittle to float atop

**Comment by bghryct** [comment]
We may try this at the end.

**Comment by bghryct** [comment]
having tried this I feel like the concavity would be a bit jarring. We're going to try raising the tittles instead.

**Comment by bghryct** [comment]
We've raised the tittles to the height of the other diacritics. This resolves this issue.
