### ISSUE TITLE
Fixing the diacritics (size, design and position)

### ISSUE THREAD

**Issue by LauraMeseguer** [Afrotype/festacrevival#17]
**Changes in these diacritics**

acutecomb: bigger size
brevecomb: reduced 95%. Relocation of the _top anchor (needs to be placed at the same position)
brevecomb_acutecomb: reduced size of the acute + Relocation of the _top anchor
brevecomb_gravecomb: reduced size of the grave + Relocation of the _top anchor
brevecomb_hookabovecomb: reduced hook 85%. Relocation of the _top anchor (needs to be placed at the same position)
brevecomb_tildecomb: reduced tilde 85%. Relocation of the _top anchor (needs to be placed at the same position)
caroncomb: same size as circumflexcomb
circumflexcomb_acutecomb: reduced size of the acute
circumflexcomb_gravecomb: reduced size of the grave
circumflexcomb_hookabovecomb: reduced hook 85%
circumflexcomb_tildecomb: reduced tilde 85%
dotbelowcomb: reduced 90%
dblgravecomb: design matched with gravecomb
dieresismacron: narrower macron
macroncomb: much higher + Relocation of the _top anchor
dotaccentcomb:  reduced 90%
hookabovecomb: relocated position
breveinvertedcomb: relocated position
ringcomb: taller
ringbelowcomb: taller
ogonekcomb: change of design (with contrast)
tildecomb: bigger! acutecomb: bigger size
brevecomb: reduced 95%. Relocation of the _top anchor (needs to be placed at the same position)
brevecomb_acutecomb: reduced size of the acute + Relocation of the _top anchor
brevecomb_gravecomb: reduced size of the grave + Relocation of the _top anchor
brevecomb_hookabovecomb: reduced hook 85%. Relocation of the _top anchor (needs to be placed at the same position)
brevecomb_tildecomb: reduced tilde 85%. Relocation of the _top anchor (needs to be placed at the same position)
caroncomb: same size as circumflexcomb
circumflexcomb_acutecomb: reduced size of the acute
circumflexcomb_gravecomb: reduced size of the grave
circumflexcomb_hookabovecomb: reduced hook 85%
circumflexcomb_tildecomb: reduced tilde 85%
dotbelowcomb: reduced 90%
dblgravecomb: design matched with gravecomb
dieresismacron: narrower macron
macroncomb: much higher + Relocation of the _top anchor
dotaccentcomb:  reduced 90%
hookabovecomb: relocated position
breveinvertedcomb: relocated position
ringcomb: taller
ringbelowcomb: taller
ogonekcomb: change of design (with contrast)
tildecomb: bigger! 
slash_part: recolocated
_leftcaphook.part: different design, according to the ogonek
————

**Hook changed in all this characters**

Design and potistion (to be discussed)

Bhook
Chook
Dhook
Fhook
Ghook
Hhook
Ihookabove
Khook
Nhookleft
Phook
Qhooktail
Thook
Tretroflexhook
Vhook
Whook
Yhook
bhook
chook
dhook
ghook
hhook
khook
nhookleft
phook
qhooktail
rfishhook
thook
tretroflexhook
vhook
whook
yhook
————

**Macron changed in these characters**
Umacrondieresis
Adieresismacron
Adotmacron
Emacronacute
Emacrongrave
Odieresismacron
Odotaccentmacron
Omacronacute
Omacrongrave
Otildemacron
Udieresismacron
Umacrondieresis
adieresismacron
adotmacron
emacronacute
emacrongrave
odieresismacron
odotaccentmacron
omacronacute
omacrongrave
otildemacron
udieresismacron
umacrondieresis
———

**Reposition of the dot below**
ydotbelow

**Comment by LauraMeseguer** [comment]
I will continue with the hooks, and upload a file

**Comment by LauraMeseguer** [comment]
[Festac_laura_20231218.glyphs.zip](https://github.com/Afrotype/festacrevival/files/13709245/Festac_laura_20231218.glyphs.zip)

**Comment by bghryct** [comment]
are these changes in the file you've attached here? Shall I merge and commit them? @LauraMeseguer @Afrotype

**Comment by LauraMeseguer** [comment]
If @Afrotype are ok with those, yes please :)

**Comment by Afrotype** [comment]
Yes please. These look good! Thanks @LauraMeseguer

**Comment by bghryct** [comment]
merged.
