### ISSUE TITLE
Festac still needs to be renamed

### ISSUE THREAD

**Issue by tphinney** [Afrotype/festacrevival#19]
I think y’all went with “Seventy Seven” as the final name? Still open to something else if you like. It cannot have a hyphen (not Seventy-Seven or Seventy-seven) nor an intercap (not SeventySeven except in the PostScript FontName as that has no spaces).

The renaming should affect:
- [x] all INTERNAL names in the font
- [x] the font file name
- [x] the name of the repo
- [x] the Glyphs file name
- [x] anything else you come across during production/development

When it comes to renaming a file in the repo and keeping its history, this needs to be done through Github itself. Mirko or I can help you with this, ideally you don’t just delete the old file and add the new one. This would be important for the GlyphsApp (.glyphs) file in particular.

**Comment by bghryct** [comment]
Renamed to Tac
