### ISSUE TITLE
Kerning

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/festacrevival#22]
Not sure if kerning is still in early stages or if we should be reviewing it now, I’ll note what I spot in this thread either way.

**Comment by samarskaya** [comment]
OW loose

**Comment by samarskaya** [comment]
T + straight (H, I, etc) is too tight, so adjusting T's rsb and then kerning in when it's next to rounds and other letters might be the way (compare EP to TI)

**Comment by samarskaya** [comment]
TY is slightly odd, where TT and TZ crash into each other completely it looks nice though, so just reviewing T overall is probably best

**Comment by bghryct** [comment]
Kerning should start soon. Good notes.
