### ISSUE TITLE
Financial Symbols

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/festacrevival#25]
The € bars could go further to the left / be more visible.

**Comment by samarskaya** [comment]
The £ cross-bar is thick whereas all other currency bars are thin, I’d thin it here too.

**Comment by samarskaya** [comment]
The ₪ is too tall (it should be shorter than cap height)

**Comment by samarskaya** [comment]
All the other double-bars seem consistent with how much space there is between them, but ₡ are super tight and ₹ rather wide. I’d adjust to where the others are.

**Comment by samarskaya** [comment]
The ƒ might want a thin bar to match the other currency and show itself as a monetary sign.

**Comment by samarskaya** [comment]
The ₱ bowl could use vertical space to give more room for the bars.

**Comment by samarskaya** [comment]
The ₫ could use a smaller bowl to give more room around the cross-bar.

**Comment by samarskaya** [comment]
₭ looks a lil messy on the right side. I’d adjust the diagonals to give more room for the crossbar.

**Comment by samarskaya** [comment]
¥ center can move up to give more room for the bars to do their crossing.

**Comment by samarskaya** [comment]
Possibly lower the crossbars on ₦

**Comment by bghryct** [comment]
I believe these have been addressed. We're reviewing them presently.

**Comment by bghryct** [comment]
completed.
