### ISSUE TITLE
Feedback on the consistency of Tac 20240205

### ISSUE THREAD

**Issue by LauraMeseguer** [Afrotype/festacrevival#26]
Hello! Here you have my suggestions and the file

A group: Check that all the characters have a correct kerning group, or any
Acircumflex and Acircumflexacute: match the circumflex
Ocircumflex and O
circumflexgrave: match the circumflex
AE: matched shape of A
Cstroke: considering changuing the angle of the stroke (I kept the original as a layer)
Hbar: recover the original H  (I kept the original as a layer)
Ldoublebar: sidebearings! 
Thook: reshaped
Tretroflexhook:  reshaped
Udieresisbelow: reposition of the dieresis
——
acircumflex and acircumflexacute: match the circumflex
ocircumflex and ocircumflexgrave: match the circumflex
bdotaccent: reposition of the b / erase kerning on the left
ddotaccent: reposition of the d / erase kerning on the left
nhookleft: reshaped
nlongrightleg: reshaped and kening group
[Tac20240205_Laura.glyphs.zip](https://github.com/Afrotype/tac/files/14169361/Tac20240205_Laura.glyphs.zip)

**Comment by bghryct** [comment]
done
