### ISSUE TITLE
lowercase z needs redraw

### ISSUE THREAD

**Issue by tphinney** [Afrotype/festacrevival#3]
The lowercase “z” needs a redraw, for sure. The cap and lowercase S use the same form, the lowercase z could look like the cap and it would be fine. The current reversed s shape is not working so well.

**Comment by tphinney** [comment]
It would also be OK to try some other treatment entirely. Just saying that the current version is not working so well.

**Comment by Afrotype** [comment]
<img width="1792" alt="Screenshot 2023-11-23 at 12 09 34 AM" src="https://github.com/Afrotype/festacrevival/assets/19597312/86e99170-2185-4641-ad47-6da656a41657">
 
Hi @tphinney. I worked on two variations of different widths. Do any of these work any better? I prefer the one on the right.

**Comment by Afrotype** [comment]
We tried a smaller, more traditional lowercase z some iterations back and it felt distant from the visual language of the rest of the letters.

Here's a screenshot of all three. @tphinney 
<img width="1792" alt="Screenshot 2023-11-23 at 12 23 26 AM" src="https://github.com/Afrotype/festacrevival/assets/19597312/6d40e34c-31ce-47c0-9ed1-66356718b5cf">

**Comment by Afrotype** [comment]
I think lowercase z is in a good place now @tphinney. Thanks for all your feedback. Can you please take a look at [the proof](https://github.com/Afrotype/festacrevival/issues/11#issue-2008234903) and let me know what you think?

**Comment by tphinney** [comment]
I think it looks pretty good. My only concern is that the lowercase z seems to lean left a bit, both in general, and compared to the cap Z. That is easily tweaked, though.

**Comment by Afrotype** [comment]
Thanks @tphinney! I agree and I've made adjustments. Gonna upload a more up-to-date proof later today. Lots of updates!
