### ISSUE TITLE
Is the “r” working, or not?

### ISSUE THREAD

**Issue by tphinney** [Afrotype/festacrevival#4]
I have some reservations about the lowercase r, when I see it in text, or by itself. I can recognize it if it is clearly an “r” by context, but if I don’t know what it is, I am not sure I would recognize it.

That said, I think the general shape/choice is bold and ambitious, and fits the typeface. Rather than a completely different approach, I wonder if it could just be given a little more curve so it arches over to the right just a bit more?

**Comment by Afrotype** [comment]
<img width="1344" alt="Screenshot 2023-11-20 at 7 39 57 PM" src="https://github.com/Afrotype/festacrevival/assets/19597312/dc8dd2b2-d4ec-4991-a797-b07a7ea64f10">
<img width="1525" alt="Screenshot 2023-11-20 at 7 58 22 PM" src="https://github.com/Afrotype/festacrevival/assets/19597312/70380955-9a90-48aa-a3e4-275ba9a34314">

Hi @tphinney @bghryct . I've given the ear/terminal(?) of the "r" slightly more curve.

**Comment by tphinney** [comment]
I am thinking it needs a bit more than that.
Also, the top of the “r” narrows a lot. This seems different than any other glyph?
So perhaps you could move just the top right point to the right another 20-30 units, perhaps? Solve both issues with the shape at once.

**Comment by Afrotype** [comment]
Thanks @tphinney! So I experimented with your suggestion(left) but I also created a version similar to what we have right now but with a widening taper versus a closing one(right). I worry that extending the top right points to the right creates a lot of space underneath that affects colour. Looking forward to more feedback. 

<img width="1792" alt="Screenshot 2023-11-23 at 12 44 59 AM" src="https://github.com/Afrotype/festacrevival/assets/19597312/8fd2880e-3e0d-4d7d-bc00-4dc7d020851e">

**Comment by tphinney** [comment]
Well, the wider “r” affects the color most troublingly in the “ra” combination (and also “rr”)—and it happens that your test string has that combination four times in a row in the top line. I think “ra” just needs kerning, as the r sticks out right where the a retreats. But the lower lines all look better on the left, I would say!

A “normal” Latin font has a much longer arm on the “r” than either of these—this is just what differentiates the “r” as a shape from other Latin letterforms. If you are not convinced, there is nothing wrong with getting a second opinion from Mirko or one (or more) of your other mentors, though. This is definitely a judgment call, and I am not claiming a monopoly on the typographic truth here!  😃

**Comment by Afrotype** [comment]
Thanks @tphinney! I totally see how kerning solves the colour problem. We'll keep an eye on it!
Thanks again!
