### ISSUE TITLE
uppercase  E  Z  

### ISSUE THREAD

**Issue by LauraMeseguer** [Afrotype/festacrevival#6]
Hello! Today I commented to the group about the possibility of defining the shape of the capital E as the lowercase, same for the Z, once the lowercase shape is reviewed

**Comment by bghryct** [comment]
More like the cap C then? What are your thoughts on EF consistency in that case?

**Comment by LauraMeseguer** [comment]
More as applying the principles of a unicase font as they do with M and N. E and F don't have the contrast that they apply in others letters.

**Comment by Afrotype** [comment]
Thanks @LauraMeseguer! I think we've resolved this, so I'm gonna close.
