### ISSUE TITLE
Suggestions for the 2,3,5

### ISSUE THREAD

**Issue by traviskochel** [Afrotype/festacrevival#7]
Here are a few quick suggestions for the 2,3,5. There are likely other ways to solve it, but I think the general goal to solve is how to make them feel a little more balanced. The 2 and 5 might be able to be solved by just angling the stroke a little. The 3 might use some exploration of a different form. I think the top stroke adds feels a little out of place and adds too much negative space to the left side.

<img width="481" alt="Screen Shot 2023-11-20 at 2 36 37 PM" src="https://github.com/Afrotype/festacrevival/assets/980360/a333c612-20a9-4381-9043-fbddf0bbb63a">

**Comment by LauraMeseguer** [comment]
Hi Travis! I agree with  your suggestions as well :)

**Comment by bghryct** [comment]
The 3 idea is novel and would fit better with the 5. fully agreed

**Comment by traviskochel** [comment]
Hi Laura!

**Comment by davidjamesudoh** [comment]
Hi @traviskochel I explored the new form suggestion for 3 and also made some changes to 2 & 5
<img width="527" alt="Screenshot 2023-11-21 at 21 00 13" src="https://github.com/Afrotype/festacrevival/assets/24567313/925d4977-8dbb-40c4-874c-a96d0af189bd">

**Comment by bghryct** [comment]
More overlap similar to how the 8 works especially where the top strokes meet the bottom strokes on the 3 and the 5 may improve things. I think the 2 could use more tension, feels a bit airy, but then again the only way to know is to see all of the numbers in strings against other numbers, and then also set in strings of text.

**Comment by traviskochel** [comment]
I like where these are going! I agree with Mirko that to evaluate it further, it would be helpful to see it in context of some other numbers or text.

**Comment by davidjamesudoh** [comment]
@bghryct @traviskochel 
<img width="704" alt="Screenshot 2023-11-22 at 11 27 43" src="https://github.com/Afrotype/festacrevival/assets/24567313/9ebb0a23-0cfb-4c66-8003-dd659a440d7a">
<img width="531" alt="Screenshot 2023-11-22 at 11 30 33" src="https://github.com/Afrotype/festacrevival/assets/24567313/1bff1092-e43f-47ce-ba2a-18325381f15b">

**Comment by tphinney** [comment]
Ooh, these are really coming together!

Right now on the 2, the top feels a bit pinched, and the right-side curve is a bit lumpy. I think the top right point on the two could move to the right a bit and fix both those issues at once.

**Comment by traviskochel** [comment]
Coming along great! If you change the pinching in the `2`, I would change the bottom of `3` and `5`, to feel similar.

One other note, the `8` feels like it's leaning forward to me. It might be good to try shifting top half to the left a little?

**Comment by tphinney** [comment]
Hmmm. The 4 has the opposite problem: the top is a little bit too heavy, swells more than needed.

**Comment by bghryct** [comment]
Take a look at the most recent proof, but I think this is coming along in a really positive direction. @tphinney we will take a look at your recommendations and try to implement them as well. I'll close this as soon as everyone agrees the numbers are "done done"

**Comment by samarskaya** [comment]
Since this thread is still open, and looks like numbers are on a further revision. They're looking much nicer, but some could use some left-right balancing. 

The 2 top should move to the right in the OSF (looks good in lining)
The 3 top should move to the right (both OSF and lining)

**Comment by bghryct** [comment]
adjusted.
