### ISSUE TITLE
Proportions/counters consistency

### ISSUE THREAD

**Issue by traviskochel** [Afrotype/festacrevival#8]
I think it would be good to take pass on proportions and counters. 

A few quick examples that are popping out to me:

The counters of the `ODQo` stand out quite a bit, compared to other counters and so might be too wide. maybe in `vGA` too. 

The counters of `ae` feel a bit small/narrow compared to the `n`.

**Comment by bghryct** [comment]
I think the counter consistency has improved and if you agree I think this can be closed as completed.
