### ISSUE TITLE
add lowercase spacing page to proof 

### ISSUE THREAD

**Issue by traviskochel** [Afrotype/festacrevival#9]
Maybe I missed it, but it would be helpful to have a page in the proof where you could better evaluate the spacing. Similar to how you have this one below for the uppercase.

<img width="687" alt="Screen Shot 2023-11-20 at 2 43 05 PM" src="https://github.com/Afrotype/festacrevival/assets/980360/898225a3-d405-47dc-bf52-d91361eb16f6">

In lowercase, rather than `HH` `OO` for context, I usually use `non` `ono`. Like this: `non[glyph]non ono[glyph]ono`.

**Comment by bghryct** [comment]
@Afrotype this should be an easy fix. Also perhaps using some of the strings that are found on the impallari testing page 
https://www.impallari.com/testing/ in the kern tab would probably be useful to see cap to lowercase etc.

**Comment by Afrotype** [comment]
Thanks @traviskochel . Uploaded the most recent proof [here](https://github.com/Afrotype/festacrevival/issues/11).

**Comment by bghryct** [comment]
This is completed so I'm closing it as complete.
